# Generated by Django 4.2.6 on 2023-11-29 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizacao',
            fields=[
                ('idOrganizador', models.IntegerField(primary_key=True, serialize=False)),
                ('pj_pf', models.CharField(max_length=40)),
                ('cpf_cnpj', models.IntegerField(max_length=14)),
                ('endContsocial', models.CharField(max_length=50)),
                ('docOrganizacao', models.BinaryField()),
                ('nomeOrg', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('nomeProjeto', models.CharField(max_length=40)),
                ('descProjeto', models.CharField()),
                ('endProjeto', models.CharField(max_length=50)),
                ('fotosProj', models.BinaryField()),
                ('idProjeto', models.AutoField(primary_key=True, serialize=False)),
                ('idOrganizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('imagemPerfil', models.BinaryField(null=True)),
                ('endereco', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('admGeral', models.BooleanField(default=False)),
                ('admOrg', models.BooleanField(default=False)),
                ('admInter', models.BooleanField(default=False)),
                ('idOrganizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organizacao')),
                ('idProjeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projeto')),
            ],
        ),
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
