# Generated by Django 4.2.6 on 2023-11-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organizacao_projeto_usuario_delete_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='cpf_cnpj',
            field=models.IntegerField(),
        ),
    ]
