# Generated by Django 4.2.6 on 2023-11-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='cpf_cnpj',
            field=models.CharField(),
        ),
    ]
