# Generated by Django 4.2.6 on 2023-11-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organizacao_cpf_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
    ]
