# Generated by Django 4.2.6 on 2023-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='idOrganizador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
