# Generated by Django 4.2.6 on 2023-12-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_organizacao_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='responsavel',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
