# Generated by Django 4.2.6 on 2023-12-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_organizacao_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='responsavel_projeto',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
