# Generated by Django 4.2.6 on 2023-12-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_projeto_responsavel_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='docOrganizacao',
            field=models.CharField(null=True),
        ),
    ]
