# Generated by Django 4.2.6 on 2023-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_organizacao_docorganizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='fotosProj',
            field=models.CharField(null=True),
        ),
    ]
