-- Generated by the database client, not guaranteed complete.
CREATE TABLE app_datasolmodel.datasolicitada(
    id SERIAL NOT NULL,
    datasolicitada date NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX app_datasolmodel_datasolicitada_key ON "app_datasolmodel.datasolicitada" USING btree ("datasolicitada");